import time
import hmac
import hashlib
from siwe import SiweMessage
import base64
import jwt
from config import ACCESS_SECRET
from utils import build_response, utc_interval

#after 5 minutes the nonce is considered invalid
# = if its been more than 5 minutes since we requested the signature from the user, 
# (we got answer late) then its invalid

NONCE_EXPIRY = 300 

def generate_nonce():
    #get the current time
    timestamp = str(int(time.time()))
    #generate msg by converting it to bytes
    msg = timestamp.encode()
    private_key = ACCESS_SECRET.encode()
    
    #sign the msg with the secret key
    #takes binary output and converts to hex string
    signature = hmac.new(
        private_key,
        msg,
        hashlib.sha256 #hashing algorithm
    ).hexdigest()

    #the nonce is the combination of the timestamp and the signature
    nonce = f"{timestamp}:{signature}"
    #convert it to only number - _ format base64string
    #returns bytes so decode to string
    return nonce


def verify_nonce(raw_nonce):
    """
    verify that the nonce is the one that we created above
    """
    msg_nonce = base64.urlsafe_b64decode(raw_nonce).decode()
    #verify that the nonce is the one that we sent
    parts = msg_nonce.split(":")
    if len(parts)!= 2:
        raise ValueError("Invalid nonce format")
    
    #timestamp : sig that was in the nonce provided by the msg
    timestamp, msg_sig = parts

    #1. the ground truth sig for nonce signed by us
    expected_sig = hmac.new(
        ACCESS_SECRET.encode(),
        timestamp.encode(),
        hashlib.sha256
    ).hexdigest()

    if not hmac.compare_digest(msg_sig, expected_sig):
        raise ValueError("Signature in nonce did not match expected value")
    
    #2. the timestamp is valid (the nonce was generated >5 min ago)
    #unit is seconds (seconds since 1/1/1970)
    if time.time() - int(timestamp) > NONCE_EXPIRY:
        raise ValueError("Timeout error; nonce timestamp is invalid")

def verify_msg(msg, wallet_signature):
    """
    verifies that the nonce included was generated by the server
    verifies that the nonce is fresh
    verifies that the message was signed by the derived wallet address
    """
    siwe_message = SiweMessage.from_message(msg)
        
    #1. check nonce authenticity (msg signed was one requested by the server)
    #parse the siwe message
    raw_nonce = siwe_message.nonce
    verify_nonce(raw_nonce)

    #2. verify that the wallet address in the msg corresponds to the 
    # one derived from the public key recovered by the provided signature and msg
    siwe_message.verify(wallet_signature)

    #returns the wallet address if every check passed
    return siwe_message.address

def generate_jwt_refresh(address):
    """
    sub: (subject) who = the wallet address
    iat: issued at (unix ts of when token was issued)
    exp: when the token expires (unix ts)

    jwt encode encodes  
    header: ex. {"alg":"HS256"} (base 64 encoded)
    payload: {"sub": "0xAB..", "iat: ..", "exp:..."} (base 64 encoded)
    signature: encoding_alg(header + "." + payload, ACCESS_SECRET)
    and returns the base64 encoded "{header}.{payload}.{signature}"
    """

    refresh_token = jwt.encode(
        {
            "sub": address,
            "iat": int(time.time()),
            "exp": int(time.time()) + utc_interval(weeks=1)
        },
        ACCESS_SECRET,
        algorithm="HS256"
    )

    return refresh_token


def generate_jwt_access(address):
    """
    sub: (subject) who = the wallet address
    iat: issued at (unix ts of when token was issued)
    exp: when the token expires (unix ts)

    jwt encode encodes  
    header: ex. {"alg":"HS256"} (base 64 encoded)
    payload: {"sub": "0xAB..", "iat: ..", "exp:..."} (base 64 encoded)
    signature: encoding_alg(header + "." + payload, ACCESS_SECRET)
    and returns the base64 encoded "{header}.{payload}.{signature}"
    """

    access_token = jwt.encode(
        {
            "sub": address,
            "iat": int(time.time()),
            "exp": int(time.time()) + utc_interval(minutes=20)
        },
        ACCESS_SECRET,
        algorithm="HS256"
    )

    return access_token

def validate_jwt_refresh(jwt_token):
    """
    1. Browser sends cookie in the form of Cookie: "vault_access=eyJB..."
    2. we extract and parse the string into the format of a dict of token_name: jwt token
    3. when we call jwt.decode(token, ACCESS_SECRET), it
        splits the token into header, payload, sig
        encodes encoding_alg (from header) alg(header + "." + payload)
        then compares it to sig. If its correct, and exp is valid, it returns the decoded payload. 
        If not, it throws and error corrsponding to the reason of invalidity
    Returns address 
    """
    print(jwt_token)
    try:
        payload = jwt.decode(jwt_token, ACCESS_SECRET, algorithms=["HS256"])
        address = payload["sub"]
        
    except jwt.InvalidSignatureError:
        return build_response(401, {"error_code": "InvalidSignatureError"})
    except jwt.ExpiredSignatureError:
        return build_response(401, {"error_code": "ExpiredSignatureError"})
    except Exception:
        return build_response(401, {"error_code": "jwt token invalid."})
    
    return {"address" : address}